version: "3.8"

services:
  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    # environment:
    #   - DATABASE_URL=postgres://user:password@db:5432/mydb
    # depends_on:
    #   - db
    restart: always
#   db:
#     image: postgres:15
#     container_name: postgres-db
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydb
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: always

# volumes:
#   postgres_data:
