version: "3.8"

services:
  web:
    build: .
    container_name: atak-web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://atak_user:atak_pass@atak-db:5432/atak_db
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: always
    # Database migration ve start script
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for database..."
        npx prisma db push
        echo "Database ready, starting application..."
        node server.js

  db:
    image: postgres:15
    container_name: atak-db
    environment:
      POSTGRES_USER: atak_user
      POSTGRES_PASSWORD: atak_pass
      POSTGRES_DB: atak_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atak_user -d atak_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: always

volumes:
  postgres_data:
